"""add tutorial_step to accounts

Revision ID: 04cb2592ee2a
Revises: 7ba61c4ee9ea
Create Date: 2026-03-27 20:54:54.885191

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '04cb2592ee2a'
down_revision: str | Sequence[str] | None = '7ba61c4ee9ea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutorial_step', sa.Integer(), server_default='0', nullable=False))

    # Mark all existing accounts as tutorial-complete so they skip it
    op.execute("UPDATE accounts SET tutorial_step = 7")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('tutorial_step')

    # ### end Alembic commands ###
