"""Remove vestigial DungeonNode model and node_id FK from expedition_node_results

Revision ID: 4f8a653f70c6
Revises: 0a23c8aaac7c
Create Date: 2026-03-22 15:13:22.489375

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4f8a653f70c6'
down_revision: str | Sequence[str] | None = '0a23c8aaac7c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop the node_id column (and its FK) first, then the referenced table.
    # batch_alter_table handles SQLite's lack of ALTER TABLE by recreating the table.
    with op.batch_alter_table('expedition_node_results', schema=None) as batch_op:
        batch_op.drop_column('node_id')

    op.drop_table('dungeon_nodes')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expedition_node_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'dungeon_nodes', ['node_id'], ['id'])

    op.create_table('dungeon_nodes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('difficulty', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
