"""add auto_delve fields to parties

Revision ID: 57b4abf09ca0
Revises: c02d9dafb5c2
Create Date: 2026-03-17 00:40:17.746415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b4abf09ca0'
down_revision: Union[str, Sequence[str], None] = 'c02d9dafb5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_delve_healed', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('auto_delve_full', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parties', schema=None) as batch_op:
        batch_op.drop_column('auto_delve_full')
        batch_op.drop_column('auto_delve_healed')

    # ### end Alembic commands ###
