"""baseline plus add death_party_name to adventurers

Revision ID: 734d0b72d556
Revises: 
Create Date: 2026-03-14 19:15:56.968521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734d0b72d556'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventurers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('death_party_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventurers', schema=None) as batch_op:
        batch_op.drop_column('death_party_name')

    # ### end Alembic commands ###
