"""add dungeon_level_names to keep

Revision ID: 7ba61c4ee9ea
Revises: fa1bdbd3c1a9
Create Date: 2026-03-26 13:53:31.340894

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ba61c4ee9ea'
down_revision: str | Sequence[str] | None = 'fa1bdbd3c1a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keeps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dungeon_level_names', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keeps', schema=None) as batch_op:
        batch_op.drop_column('dungeon_level_names')

    # ### end Alembic commands ###
