"""add decision_day to expeditions

Revision ID: 80fae7659954
Revises: 264e6d2e5d63
Create Date: 2026-03-15 20:57:12.673095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80fae7659954'
down_revision: Union[str, Sequence[str], None] = '264e6d2e5d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expeditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expeditions', schema=None) as batch_op:
        batch_op.drop_column('decision_day')

    # ### end Alembic commands ###
