"""add bonus column to magic_items

Revision ID: c02d9dafb5c2
Revises: 975013bba339
Create Date: 2026-03-16 22:02:33.708001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02d9dafb5c2'
down_revision: Union[str, Sequence[str], None] = '975013bba339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magic_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magic_items', schema=None) as batch_op:
        batch_op.drop_column('bonus')

    # ### end Alembic commands ###
