"""add consumable and spell_multiplier to magic_items

Revision ID: fa1bdbd3c1a9
Revises: 660af69121d4
Create Date: 2026-03-25 11:44:23.255924

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa1bdbd3c1a9'
down_revision: str | Sequence[str] | None = '660af69121d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magic_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumable', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('spell_multiplier', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('magic_items', schema=None) as batch_op:
        batch_op.drop_column('spell_multiplier')
        batch_op.drop_column('consumable')

    # ### end Alembic commands ###
